### ISSUE TITLE
Migrate script funktioniert bei mir nicht (master branch)

### ISSUE THREAD

**Issue by thomase1993** [studentenportal/web#196]
Die Installation an sich hat grundsätzlich funktioniert. Das Projekt konnte ich noch nie ausführen (bin neu in Python). Unten der Code mit Fehlermeldung.

thomas ~/PycharmProjects/web $ python manage.py migrate
Running migrations for easy_thumbnails:
- Nothing to migrate.
 - Loading initial data for easy_thumbnails.
Installed 0 object(s) from 0 fixture(s)
Running migrations for oauth2:
- Nothing to migrate.
 - Loading initial data for oauth2.
Installed 0 object(s) from 0 fixture(s)
Running migrations for front:
- Nothing to migrate.
 - Loading initial data for front.
Installed 0 object(s) from 0 fixture(s)
Running migrations for documents:
 - Migrating forwards to 0003_auto__add_field_document_flattr_disabled.
 > documents:0001_initial
Error in migration: documents:0001_initial
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/thomas/PycharmProjects/web/apps/documents/migrations/0001_initial.py", line 15, in forwards
    ('description', self.gf('django.db.models.fields.CharField')(max_length=255)),
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 356, in create_table
    for field_name, field in fields
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 670, in column_sql
    sql = field.db_type()
TypeError: db_type() takes exactly 2 arguments (1 given)

**Comment by fabianhauser** [comment]
Wir arbeiten momentan an der Dockerisierung vom Studentenportal, damit das ganze einfacher zu Installieren ist. Für die Entwicklungsumgebung sollte das inzwischen ziemlich Problemlos funktionieren.
Du findest den letzten Stand im Branch `docker` bzw. im Pull Request #190 sowie eine kurze Anleitung zum starten [hier](https://github.com/studentenportal/web/blob/docker/docs/development.md#einrichten-der-entwicklungsumgebung).

Könntest du mal ausprobieren, ob das bei dir funktioniert? Wir sind sehr froh um Feedback!

**Comment by thomase1993** [comment]
Teste ich grad mal. Lieber wäre es mir, wenn docker in vagrant läuft. :-)
Ein kollege schaffte mal ein bluescreen mit docker + vmware player

**Comment by thomase1993** [comment]
Also diese Parts haben wunderbar funktioniert:
```
git clone https://github.com/studentenportal/web.git studentenportal
cd studentenportal
make start-dev
Das Studentenportal ist jetzt unter http://localhost:8000 verfügbar.
Bei Änderungen am Code, kannst du das Studentenportal mit make restart-dev neu starten.
```
make musste ich mit root rechten ausführen. Bei mir läuft es jetzt auf einer Dockerinstanz in einer Vagrant-VM. (Bei Intresse einfach pullen). Die 2 zusätzlichen Scripte sollten auch nicht stören beim "normalen" Einrichten.

**Comment by fabianhauser** [comment]
Super, freut mich zu hören, dass es funktioniert. Können wir dieses Issue in diesem Fall als resolved betrachten?
Betr. Vagrant: mir ist nicht ganz klar, wo der Vorteil von Docker in Vagrant gegenüber von Docker Nativ (boot2docker auf Windows&Mac) liegt?

**Comment by thomase1993** [comment]
Da läuft dann docker vollständig in einer vm. Ein Vorteil ist, dass jeder das gleiche bsys hat und alles automatisch installiert ist. Ausserdem habe ich schon von Problemen gehört, wenn man docker und vmware/virtualbox paralell betreibt. Man könnte noch diverse Sicherheitsaspekte erwähnen, die bei einer Entwicklerinstallation jedoch nicht relevant sind.

Von vagrant:
The Vagrant Docker provisioner can automatically install Docker, pull Docker containers, and configure certain containers to run on boot.

Vagrant kann man aber auch "nur" benutzen, um z.B beim ersten Start ein sh script auszuführen, das netzwerk mit forwarding, ssh usw. einzurichten

**Comment by dbrgn** [comment]
Wo liegt denn der Unterschied zu [boot2docker](http://boot2docker.io/)? Da gibt's auch eine VM mit dem Docker Daemon drin. Nur ist sie so klein, dass sie im Gegensatz zu einem doch ziemlich fetten Ubuntu innerhalb von ca. 5 Sekunden gestartet ist.

Das betrifft natürlich eh nur Leute die auf Windows oder Mac OS entwickeln. Unter Linux ist es wohl am sinnvollsten, direkt Docker zu verwenden.

**Comment by thomase1993** [comment]
stimmt da sehe ich kein Unterschied.

**Comment by thomase1993** [comment]
Aber bei vagrant kann man natürluch das bsys je nach Einsatz im Projekt ändern :-)
